addons:
  apt:
    packages:
    - lftp
    - lib32z1
    - lib32stdc++6

language: c

sudo: false

env:
  - VERSION=1.7
  - VERSION=1.8
  - VERSION=1.9

script:
  - 'if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then bash ci/build.sh $VERSION "dev" $FTP_HOST $FTP_USER $FTP_PASS; fi'
  - 'if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then bash ci/test.sh $VERSION "dev"; fi'

